# Generated by Django 3.0.2 on 2020-02-18 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='couponSlug',
            field=models.SlugField(default='coupon slug', max_length=25),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discountPercentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='promote',
            name='discountPercentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
