# Generated by Django 3.0.2 on 2020-02-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0002_auto_20200219_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
