# Generated by Django 3.0.2 on 2020-03-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0002_soldcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='country',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='email',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='fax',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='service_area',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='telephone',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='term_of_use',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='website',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
