# Generated by Django 3.0.2 on 2020-02-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0004_auto_20200219_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='coupon',
            field=models.ManyToManyField(to='couponApp.Coupon'),
        ),
    ]
