# Generated by Django 3.0.2 on 2020-03-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0004_auto_20200308_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
