# Generated by Django 3.0.2 on 2020-03-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0006_auto_20200308_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='email',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
