# Generated by Django 3.0 on 2020-02-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0006_orderitem_quantity'),
        ('couponApp', '0002_cp'),
    ]

    operations = [
    ]
