# Generated by Django 3.0.2 on 2020-03-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0007_auto_20200308_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='email',
        ),
    ]
