# Generated by Django 3.0 on 2020-02-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0007_merge_20200221_0236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CP',
        ),
    ]
