# Generated by Django 3.0.2 on 2020-03-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0008_remove_coupon_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='email',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
