# Generated by Django 3.0.2 on 2020-03-14 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0009_coupon_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='store',
        ),
        migrations.AddField(
            model_name='coupon',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='couponApp.Brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
