# Generated by Django 3.0.2 on 2020-03-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0010_auto_20200313_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='coupons',
        ),
    ]
