# Generated by Django 3.0.2 on 2020-02-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0010_auto_20200221_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
