# Generated by Django 3.0.2 on 2020-03-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0011_remove_brand_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='fax',
            field=models.TextField(blank=True, help_text='Contact phone number'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='telephone',
            field=models.TextField(blank=True, help_text='Contact phone number'),
        ),
    ]
