# Generated by Django 3.0.2 on 2020-02-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0011_auto_20200221_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(default='None'),
            preserve_default=False,
        ),
    ]
