# Generated by Django 3.0.2 on 2020-02-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0012_coupon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='purchasedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='couponApp.User'),
        ),
    ]
