# Generated by Django 3.0.2 on 2020-02-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0013_auto_20200221_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='brand',
        ),
    ]
