# Generated by Django 3.0.2 on 2020-02-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0014_remove_orderitem_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
    ]
