# Generated by Django 3.0.2 on 2020-02-22 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0015_remove_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='couponApp.User'),
        ),
    ]
