# Generated by Django 3.0.2 on 2020-02-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0021_auto_20200221_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
