# Generated by Django 3.0.2 on 2020-02-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponApp', '0022_auto_20200221_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='couponApp.Coupon'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
